name: Meta
version: 1.1
main: fp.meta.Meta
authors: [A_FlyingPig_]
description: meta
depend:
  - Vault
commands:
  meta:
    description: main cmd
  nick:
    description: nick
permissions:
  meta.admin:
    description: main permission
    default: op
  meta.nick:
    default: op
    description: nick permission